### ISSUE TITLE
integer overflow in irods::logical_quotas::current_data_size_in_bytes

### ISSUE THREAD

**Issue by anderbubble** [irods/irods_policy_examples#4]
`logical_quotas_init` appears to set `irods::logical_quotas::current_data_size_in_bytes` incorrectly. I haven't tracked down the math to prove this, but I suspect there is an integer overflow at https://github.com/irods/irods_policy_examples/blob/master/irods_policy_logical_quotas.re#L114.

Here is an init:

```
[janderson@fox1 ~]$ irule -vr irods_rule_engine_plugin-irods_rule_language-instance 'logical_quotas_init("/civilfritz.net/home/janderson", 999999999, 999999999)' null null
rcExecMyRule: rule { logical_quotas_init("/civilfritz.net/home/janderson", 999999999, 999999999) }
outParamDesc: 
ExecMyRule completed successfully.    Output 


```

Here is the relevant value attached to the collection:

```
[janderson@fox1 ~]$ imeta ls -C /civilfritz.net/home/janderson irods::logical_quotas::current_data_size_in_bytes
AVUs defined for collection /civilfritz.net/home/janderson:
attribute: irods::logical_quotas::current_data_size_in_bytes
value: 771976736
units: 
```

But here is the same value calculated directly with `iquest`.

```
[janderson@fox1 ~]$ iquest "select SUM(DATA_SIZE) where COLL_NAME = '/civilfritz.net/home/janderson' || like '/civilfritz.net/home/janderson/%'"
DATA_SIZE = 163980733984
------------------------------------------------------------
```

Through experimental editing of the policy I have seen that the correct value gets set if I remove the `int()` typecast; but I don't know what affect that will have later at PEP, and I don't know what this means for the larger viability of performing calculations on "large" numbers.

**Comment by trel** [comment]
Closing - I believe this is now handled cleanly by the implementation at https://github.com/irods/irods_rule_engine_plugin_logical_quotas

If not, please open an issue over there...
