### ISSUE TITLE
logical quotas are vulnerable to changes by the collection owner

### ISSUE THREAD

**Issue by anderbubble** [irods/irods_policy_examples#6]
I had to set the quota using an owner of the collection. How can I set a quota that a regular user can't just alter themselves? I imagined having an admin user be the owner of the top-level collection and grant more restrictive ACLs for end-users, but I'm wondering if a user has to be able to update at least the current size values for this to work at all. If that's the case I'm concerned that the end user could just alter the current sizes themselves to bypass quota enforcement.

**Comment by trel** [comment]
Closing - I believe this is now handled cleanly by the implementation at https://github.com/irods/irods_rule_engine_plugin_logical_quotas

If not, please open an issue over there...
